SmartphoneStore.WebUI/Controllers/AdminController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SmartphoneStore.Domain.Abstract;
using SmartphoneStore.Domain.Entities;

namespace SmartphoneStore.WebUI.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private readonly ISmartphoneRepository repository;

        public AdminController(ISmartphoneRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index()
        {
            return View(repository.Smartphones);
        }

        public ViewResult Edit(int smartphoneId)
        {
            Smartphone smartphone = repository.Smartphones
                .FirstOrDefault(g => g.SmartphoneId == smartphoneId);
            return View(smartphone);
        }

        // Перегруженная версия Edit() для сохранения изменений
        [HttpPost]
        public ActionResult Edit(Smartphone smartphone, HttpPostedFileBase image = null)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    smartphone.ImageMimeType = image.ContentType;
                    smartphone.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(smartphone.ImageData, 0, image.ContentLength);
                }
                repository.SaveSmartphone(smartphone);
                TempData["message"] = string.Format("Изменения в смартфоне \"{0}\" были сохранены", smartphone.Name);
                return RedirectToAction("Index");
            }
            else
            {
                // Что-то не так со значениями данных
                return View(smartphone);
            }
        }

        public ViewResult Create()
        {
            return View("Edit", new Smartphone());
        }

        [HttpPost]
        public ActionResult Delete(int smartphoneId) 
        {
            Smartphone deletedSmartphone = repository.DeleteSmartphone(smartphoneId);
            if (deletedSmartphone != null)
            {
                TempData["message"] = string.Format("Смартфон \"{0}\" был удален",
                    deletedSmartphone.Name);
            }
            return RedirectToAction("Index");
        }
    }
}

SmartphoneStore.WebUI/Controllers/SmartphoneController.cs
using System.Linq;
using System.Web.Mvc;
using SmartphoneStore.Domain.Abstract;
using SmartphoneStore.Domain.Entities;
using SmartphoneStore.WebUI.Models;

namespace SmartphoneStore.WebUI.Controllers
{
    public class SmartphoneController : Controller
    {
        private readonly ISmartphoneRepository _repository;
        public int PageSize = 4;

        public SmartphoneController(ISmartphoneRepository repo)
        {
            _repository = repo;
        }

        public ViewResult List(string manufacturer, int page = 1)
        {
            SmartphonesListViewModel model = new SmartphonesListViewModel
            {
                Smartphones = _repository.Smartphones
                    .Where(p => manufacturer == null || p.Manufacturer == manufacturer)
                    .OrderBy(smartphone => smartphone.SmartphoneId)
                    .Skip((page - 1) * PageSize)
                    .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = manufacturer == null ?
                        _repository.Smartphones.Count() :
                        _repository.Smartphones.Count(game => game.Manufacturer == manufacturer)
                },
                CurrentManufacturer = manufacturer
            };
            return View(model);
        }

        public FileContentResult GetImage(int smartphoneId)
        {
            Smartphone smartphone = _repository.Smartphones
                .FirstOrDefault(g => g.SmartphoneId == smartphoneId);

            if (smartphone != null)
            {
                return File(smartphone.ImageData, smartphone.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

SmartphoneStore.WebUI/Views/Admin/Edit.cshtml
@model SmartphoneStore.Domain.Entities.Smartphone

@{
    ViewBag.Title = "Админ панель: редактирование товара";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="panel">
    <div class="panel-heading">
        <h3>Редактирование смартфона «@Model.Name»</h3>
    </div>

    @using (Html.BeginForm("Edit", "Admin",
        FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="panel-body">
            @Html.HiddenFor(m => m.SmartphoneId)
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                switch (property.PropertyName)
                {
                    case "SmartphoneId":
                    case "ImageData":
                    case "ImageMimeType":
                        // Ничего не делать
                        break;
                    default:
                        <div class="form-group">
                            <label>@(property.DisplayName ?? property.PropertyName)</label>
                            @if (property.PropertyName == "Description")
                            {
                                @Html.TextArea(property.PropertyName, null,
                                    new { @class = "form-control", rows = 5 })
                            }
                            else
                            {
                                @Html.TextBox(property.PropertyName, null,
                                    new { @class = "form-control" })
                            }
                            @Html.ValidationMessage(property.PropertyName)
                        </div>
                        break;
                }
            }
            <div class="form-group">
                <div style="position:relative;">
                    <label>Картинка</label>
                    <a class='btn' href='javascript:;'>
                        Выберите файл...
                        <input type="file" name="Image" size="40"
                               style="position:absolute;z-index:2;top:0;
                                left:0;filter: alpha(opacity=0); opacity:0;
                                background-color:transparent;color:transparent;"
                               onchange='$("#upload-file-info").html($(this).val());'>
                    </a>
                    <span class='label label-info' id="upload-file-info"></span>
                </div>
                @if (Model.ImageData == null)
                {
                    <div class="form-control-static">Нет картинки</div>
                }
                else
                {
                    <img class="img-thumbnail" width="150" height="150"
                         src="@Url.Action("GetImage", "Smartphone",
                        new { Model.SmartphoneId })" />
                }
            </div>
        </div>
        <div class="panel-footer">
            <input type="submit" value="Сохранить" class="btn btn-primary" />
            @Html.ActionLink("Отменить изменения и вернуться к списку", "Index", null, new
            {
                @class = "btn btn-default"
            })
        </div>
    }
</div>

SmartphoneStore.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<SmartphoneStore.Domain.Entities.Smartphone>

@{
    ViewBag.Title = "Админ панель: список товаров";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Список смартфонов</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-right">ID</th>
                <th>Название</th>
                <th class="text-right">Цена</th>
                <th class="text-center">Действия</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-right">@item.SmartphoneId</td>
                    <td>@Html.ActionLink(item.Name, "Edit", new { item.SmartphoneId })</td>
                    <td class="text-right">@item.Price.ToString("# руб")</td>
                    <td class="text-center">
                        @using (Html.BeginForm("Delete", "Admin"))
                        {
                            @Html.Hidden("SmartphoneId", item.SmartphoneId)
                            <input type="submit"
                                   class="btn btn-default btn-xs"
                                   value="Удалить" />
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Добавить смартфон", "Create", null,
            new { @class = "btn btn-default" })
    </div>
</div>