SmartphoneStore.WebUI/Controllers/CartController.cs
using System.Linq;
using System.Web.Mvc;
using SmartphoneStore.Domain.Abstract;
using SmartphoneStore.Domain.Entities;
using SmartphoneStore.WebUI.Models;

namespace SmartphoneStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private ISmartphoneRepository repository;
        private IOrderProcessor orderProcessor;

        public CartController(ISmartphoneRepository repo, IOrderProcessor processor)
        {
            repository = repo;
            orderProcessor = processor;
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Извините, ваша корзина пуста!");
            }

            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }
    
        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToRouteResult AddToCart(Cart cart, int smartphoneId, string returnUrl)
        {
            Smartphone smartphone = repository.Smartphones
                .FirstOrDefault(g => g.SmartphoneId == smartphoneId);

            if (smartphone != null)
            {
                cart.AddItem(smartphone, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int smartphoneId, string returnUrl)
        {
            Smartphone smartphone = repository.Smartphones
                .FirstOrDefault(g => g.SmartphoneId == smartphoneId);

            if (smartphone != null)
            {
                cart.RemoveLine(smartphone);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

SmartphoneStore.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SmartphoneStore.Domain.Abstract;

namespace SmartphoneStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private readonly ISmartphoneRepository _repository;

        public NavController(ISmartphoneRepository repo)
        {
            _repository = repo;
        }

        public PartialViewResult Menu(string manufacturer = null, bool horizontalNav = false)
        {
            ViewBag.SelectedManufacturer = manufacturer;
            
            IEnumerable<string> manufacturers = _repository.Smartphones
                .Select(smartphone => smartphone.Manufacturer)
                .Distinct()
                .OrderBy(x => x);

            return PartialView("FlexMenu", manufacturers);
        }
    }
}

SmartphoneStore.WebUI/Controllers/SmartphoneController.cs
using System.Linq;
using System.Web.Mvc;
using SmartphoneStore.Domain.Abstract;
using SmartphoneStore.Domain.Entities;
using SmartphoneStore.WebUI.Models;

namespace SmartphoneStore.WebUI.Controllers
{
    public class SmartphoneController : Controller
    {
        private readonly ISmartphoneRepository _repository;
        public int PageSize = 4;

        public SmartphoneController(ISmartphoneRepository repo)
        {
            _repository = repo;
        }

        public ViewResult List(string manufacturer, int page = 1)
        {
            SmartphonesListViewModel model = new SmartphonesListViewModel
            {
                Smartphones = _repository.Smartphones
                    .Where(p => manufacturer == null || p.Manufacturer == manufacturer)
                    .OrderBy(smartphone => smartphone.SmartphoneId)
                    .Skip((page - 1) * PageSize)
                    .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = manufacturer == null ?
                        _repository.Smartphones.Count() :
                        _repository.Smartphones.Count(game => game.Manufacturer == manufacturer)
                },
                CurrentManufacturer = manufacturer
            };
            return View(model);
        }

        public FileContentResult GetImage(int smartphoneId)
        {
            Smartphone smartphone = _repository.Smartphones
                .FirstOrDefault(g => g.SmartphoneId == smartphoneId);

            if (smartphone != null)
            {
                return File(smartphone.ImageData, smartphone.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

SmartphoneStore.WebUI/Views/Shared/SmartphoneSummary.Mobile.cshtml
@model SmartphoneStore.Domain.Entities.Smartphone

<div data-role="collapsible" data-collapsed="false" data-content-theme="c">
    <h2>@Model.Name</h2>
    <div>
        <div>
            @Model.Description
        </div>
        <div>
            <strong>(@Model.Price.ToString("# руб"))</strong>
        </div>
        <div>
            @using (Html.BeginForm("AddToCart", "Cart"))
            {
                @Html.HiddenFor(x => x.SmartphoneId)
                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                <input type="submit" class="btn btn-success" value="В корзину" />
            }
        </div>
    </div>
</div>

SmartphoneStore.WebUI/Views/Shared/SmartphoneSummary.cshtml
@model SmartphoneStore.Domain.Entities.Smartphone

<div class="well">
    @if (Model.ImageData != null)
    {
        <div class="pull-left" style="margin-right: 10px">
            <img class="img-thumbnail" width="75" height="75"
                 src="@Url.Action("GetImage", "Smartphone",
                          new { Model.SmartphoneId})" />
        </div>
    }

    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("# руб")</span>
    </h3>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x => x.SmartphoneId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Добавить в корзину" />
        </div>
    }
    <span class="lead">@Model.Description</span>
</div>

SmartphoneStore.WebUI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title></title>
</head>
<body>
<div>
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success">@TempData["message"]</div>
    }
    @RenderBody()
</div>
</body>
</html>

SmartphoneStore.WebUI/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"
          href="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css" />
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
<div data-role="page" id="page1">
    <div data-theme="a" data-role="header" data-position="fixed">
        <h3>GameStore</h3>
        @Html.Action("Menu", "Nav")
    </div>
    <div data-role="content">
        <ul data-role="listview" data-divider-theme="b" data-inset="false">
            @RenderBody()
        </ul>
    </div>
</div>
</body>
</html>

SmartphoneStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
    <style>
        .navbar-right {
            float: right !important;
            margin-right: 15px;
            margin-left: 15px;
        }
    </style>
</head>
<body>
<div class="navbar navbar-inverse" role="navigation">
    <a class="navbar-brand" href="#">
        <span class="hidden-xs">SmartphoneStore - магазин лучших смартфонов</span>
        <div class="visible-xs">Smartphone</div>
        <div class="visible-xs">Store</div>
    </a>
    @Html.Action("Summary", "Cart")
</div>
	
<div class="visible-xs">
    @Html.Action("Menu", "Nav", new { horizontalNav = true })
</div>
	
<div class="row panel">
    <div id="manufacturers" class="col-sm-3 hidden-xs">
        @Html.Action("Menu", "Nav")
    </div>
    <div class="col-xs-12 col-sm-8">
        @RenderBody()
    </div>
</div>
</body>
</html>